config/routes.rb
Rails.application.routes.draw do
  get 'movies', to: 'movies#index'
  get 'movies/new'
  post 'movies', to: 'movies#create'
  get 'movies/:id', to: 'movies#show'
  get 'movies/:id/edit', to: 'movies#edit', as: 'edit_movie'
  patch 'movies/:id', to: 'movies#update', as: :movie
  delete 'movies/:id', to: 'movies#destroy'
  get 'movies/:id/favorite', to: 'movies#favorite', as: 'favorite_movie'
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :find_movie, only: [:show, :edit, :update, :destroy, :favorite]
    def index
        @movies=Movie.all
    end
    
    def new
        @movie=Movie.new
    end

    def create
        @movie=Movie.new(movie_params)
        @movie.save
        redirect_to movies_path
    end

    def show
    end

    def edit
    end

    def update
        @movie.update(movie_params)
        redirect_to movies_path
    end

    def destroy
        @movie.destroy
        redirect_to movies_path
    end
    
    def favorite
        
        if @movie.favorite == true
        @movie.favorite = false
        elsif @movie.favorite == false
        @movie.favorite = true
        end
        @movie.save
        redirect_to movies_path
    end

    private

    def movie_params    
        params.require(:movie).permit(:title, :year, :favorite)
    end

    def find_movie
        @movie=Movie.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/darkly/bootstrap.min.css" rel="stylesheet" integrity="sha384-w+8Gqjk9Cuo6XH9HKHG5t5I1VR4YBNdPt/29vwgfZR485eoEJZ8rJRbm3TR32P6k" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = container>
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/edit.html.erb
<%= form_with(model: @movie, local: true) do|f|%>

<div class="form-group">
    <%= f.label 'Título:' %>
    <%= f.text_field :title, class: 'form-control'%>
</div>

<div class="form-group">
    <%= f.label 'Año:' %>
    <%= f.number_field :year, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.check_box :favorite %> 
    <%= f.label 'Agregar a películas favoritas' %> 
</div>

<%= f.submit 'Guardar' %>
<% end %>

<%= link_to "Regresar", movies_path %>

app/views/movies/index.html.erb
<h1 class = "text-center font-weight-bold">Lista de películas</h1>

<div class = 'jumbotron'>
    <h2 class = "text-center font-weight-bold">Películas Favoritas</h2>
    <div class = "row">
        <% @movies.each do|movie| %>
        <% if movie.favorite == true %>
        
        <div class= ' text-center col-md-3 mx-auto my-3'>
            <div class="card border-warning mb-3" style="max-width: 20rem;">
                <h4 class="card-header"><%= movie.title %></h4>
                <div class="card-body">
                    <p class="card-text">Película favorita</p>
                    <h5 class="card-title">Año: <%= movie.year %></h5>
                    <p class="card-text"><%= link_to "Eliminar de favoritos", favorite_movie_path(movie), class: "btn btn-outline-danger" %></p>
                    <%= link_to 'Ver', movie %>
                    <%= link_to 'Editar', edit_movie_path(movie) %>
                    <%= link_to "Borrar", movie, method: :delete, data: {confirm: 'Estás seguro?'} %>
                </div>
            </div>        
        </div> 
        <% end %>
        <% end %>  
    </div>
</div>

<div class = 'jumbotron'>
    <h2 class = "text-center font-weight-bold">Películas</h2>
    <div class = "row">
        <% @movies.each do|movie| %>
        <% if movie.favorite == false %>
        <div class= ' text-center col-md-3 mx-auto my-3'>
            <div class="card border-success mb-3" style="max-width: 20rem;">
                <h4 class="card-header"><%= movie.title %></h4>
                <div class="card-body">
                    <h5 class="card-title">Año: <%= movie.year %></h5>
                    <p class="card-text"><%= link_to "Añadir", favorite_movie_path(movie), class: "btn btn-outline-warning" %></p>
                    <%= link_to 'Ver', movie %>
                    <%= link_to 'Editar', edit_movie_path(movie) %>
                    <%= link_to "Borrar", movie, method: :delete, data: {confirm: 'Estás seguro?'} %>
                </div>
            </div>
        </div>
        <% end %>
        <% end %>
    </div>
    
</div>

<p class='text-center'><%= link_to 'Agregar nueva película', movies_new_path%></p>

app/views/movies/new.html.erb
<%= form_with(model: @movie, local: true) do|f|%>
<div class="form-group">
<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :year %>
<%= f.number_field :year, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.check_box :favorite %> 
    <%= f.label 'Agregar a películas favoritas' %> 
</div>
<%= f.submit 'Crear' %>
<% end %>

app/views/movies/show.html.erb
<%= @movie.title %>
<%= @movie.year %>
<br>
<%= link_to 'Editar', edit_movie_path(@movie) %>
<%= link_to "Borrar", @movie, method: :delete, data: {confirm: 'Estás seguro?'} %>
<%= link_to "Regresar", movies_path %>